name: Docker bind9-dev Image CI & CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker Setup QEMU
        # You may pin to the exact commit or the version.
        # uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8
        uses: docker/setup-qemu-action@v2
        with:
          # QEMU static binaries Docker image (e.g. tonistiigi/binfmt:latest)
          image: tonistiigi/binfmt:latest # optional, default is tonistiigi/binfmt:latest
          # Platforms to install (e.g. arm64,riscv64,arm)
          platforms: all # optional, default is all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/bind:dev,${{ secrets.DOCKER_HUB_USERNAME }}/bind:dev-9.16.1-2.100-20230624
          push: true
